# Workflow name
name: Project CI/CD
# Events for this workflow
on: [ push, pull_request ]

jobs:
  # Build project files
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config:
          - {
            name: "Windows Latest - GCC", artifact: "windows-gcc.tar.xz",
            os: windows-latest,
            cc: "gcc-9", cxx: "g++-9",
          }
          - {
            name: "Ubuntu Latest - GCC", artifact: "linux-gcc.tar.xz",
            os: ubuntu-latest,
            cc: "gcc-9", cxx: "g++-9"
          }
          - {
            name: "Ubuntu Latest - GCC", artifact: "linux-gcc.tar.xz",
            os: ubuntu-latest,
            cc: "gcc-9", cxx: "g++-9"
          }
      fail-fast: false

    steps:
      - name: Checkout this repository.
        uses: actions/checkout@v2

      - name: "Install NINJA"
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMAKE creates build files.
        run: |
          mkdir out
          gcc --version
          g++ --version
          echo %gcc%
          cmake -S . -B ./out/ -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMAKE build project.
        run: cmake --build ./out/ --config Release