# Workflow name
name: Project CI/CD
# Events for this workflow
on: [ push, pull_request ]

jobs:
  # Build project files
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: "Build and Test - Windows GCC", artifact: "windows-gcc.tar.xz",
            os: windows-latest,
            cc: "gcc", cxx: "g++",
          }
          - {
            name: "Build and Test - Ubuntu GCC", artifact: "linux-gcc.tar.xz",
            os: ubuntu-latest,
            cc: "gcc-9", cxx: "g++-9"
          }
          - {
            name: "Build and Test - MacOS GCC", artifact: "macos-gcc.tar.xz",
            os: macos-latest,
            cc: "gcc-9", cxx: "g++-9"
          }
      fail-fast: false

    steps:
      - name: Clang Format - Checker
        uses: RafikFarhad/clang-format-github-action@v1
        with:
          sources: "core/**/*.c,core/**/*.h,libs/**/*.c,libs/**/*.h"

      - name: Checkout this repository.
        uses: actions/checkout@v2

      - name: "Install Ninja"
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMAKE creates build files.
        run: |
          mkdir out
          cmake -S . -B ./out/ -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMAKE build project.
        run: cmake --build ./out/ --config Release

      - name: Unit tests - Google Tests
        run: ./out/tests/google-test/Google_Tests_run