# Workflow name
name: Project CI/CD
# Events for this workflow
on: [ push, pull_request ]

jobs:
  # Build project files
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        compiler: [ gcc, clang ]
      fail-fast: false

    steps:
      - name: Checkout this repository.
        uses: actions/checkout@v2

      - name: CMAKE (GCC) creates build files.
        if: ${{ matrix.compiler == gcc }}
        env:
          CC: ${{ matrix.compiler }}
          CXX: g++
        run: |
          echo "CC:\t $CC \t and CXX:\t $CXX\t"
          mkdir out
          cmake -S . -B ./out/ -DCMAKE_BUILD_TYPE=Release

      - name: CMAKE (CLANG) creates build files.
        if: ${{ matrix.compiler == clang }}
        env:
          CC: ${{ matrix.compiler }}
          CXX: clang++
          run: |
            echo "CC:\t $CC \t and CXX:\t $CXX\t"
            mkdir out
            cmake -S . -B ./out/ -DCMAKE_BUILD_TYPE=Release

      - name: CMAKE build project.
        run: cmake --build ./out/ --config Release