# Workflow name
name: Project CI/CD
# Events for this workflow
on: [ push, pull_request ]

jobs:
  # Build project files
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    steps:
      - name: Checkout this repository.
        uses: actions/checkout@v2

      - name: CMAKE creates build files.
        run: |
          mkdir out
          gcc --version
          g++ --version
          cmake -S . -B ./out/ -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++

      - name: CMAKE build project.
        run: cmake --build ./out/ --config Release